import React, { Component } from "react";
import ReactDOM from "react-dom";
import App from "./components/App";
import PostJob from "./components/PostJob";
import Comm from "./components/Comm";
import Pagination from "./components/Pagination";
import SearchForm from "./components/SearchForm";
import Routing from "./components/Routing";
import JobSingle from "./components/JobSingle";
import JobDetails from "./components/JobDetails";
