# Generated by Django 3.1 on 2020-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_remove_forum_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='job_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
